name: Deploy Backend to Azure Container Apps

on:
  push:
    branches:
      - main
    paths:
      - 'BE/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:

env:
  REGISTRY_NAME: sitruyen
  RESOURCE_GROUP: rg-sitruyen-dev
  CONTAINER_APP_ENV_NAME: env-sitruyen-dev
  CONTAINER_APP_NAME: portfolio-api
  IMAGE_NAME: portfolio-api
  DOCKERFILE_PATH: BE_Portfolio/Dockerfile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker image
      working-directory: ./BE
      run: |
        docker build -f ${{ env.DOCKERFILE_PATH }} -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }} --all-tags

    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENV_NAME }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        imageToDeploy: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        location: eastasia
